// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://julbhcnpkylursrkvajd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1bGJoY25wa3lsdXJzcmt2YWpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNDA2ODgsImV4cCI6MjA2ODkxNjY4OH0.TB7mMYg7RYUnbH9xv76N3sVyFk0Sk1TGqILC_EZXrEs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});